
version: '2'

services:
  koa-seed:
    image: koa-seed:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 index.js
